using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wealthra.Infrastructure.Persistence;

#nullable disable

namespace Wealthra.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419120000_AddRecommendationEngineAssets")]
    public partial class AddRecommendationEngineAssets : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""CREATE EXTENSION IF NOT EXISTS vector;""");

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "FinancialTips" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Topic" character varying(200) NOT NULL,
                    "Body" character varying(2000) NOT NULL,
                    "Locale" character varying(10) NOT NULL,
                    "Tags" character varying(500) NOT NULL,
                    "Embedding" vector(16) NOT NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE OR REPLACE VIEW "vw_MonthlyCategoryMetrics" AS
                WITH MonthlyIncome AS (
                    SELECT
                        "CreatedBy" AS "UserId",
                        DATE_TRUNC('month', "TransactionDate") AS "Month",
                        SUM("Amount") AS "TotalIncome"
                    FROM "Incomes"
                    GROUP BY "CreatedBy", DATE_TRUNC('month', "TransactionDate")
                ),
                MonthlySpend AS (
                    SELECT
                        e."CreatedBy" AS "UserId",
                        DATE_TRUNC('month', e."TransactionDate") AS "Month",
                        e."CategoryId",
                        c."NameEn" AS "CategoryName",
                        c."NameTr" AS "CategoryNameTr",
                        SUM(e."Amount") AS "TotalSpend"
                    FROM "Expenses" e
                    JOIN "Categories" c ON e."CategoryId" = c."Id"
                    GROUP BY e."CreatedBy", DATE_TRUNC('month', e."TransactionDate"), e."CategoryId", c."NameEn", c."NameTr"
                )
                SELECT
                    ms."UserId",
                    ms."Month",
                    ms."CategoryId",
                    ms."CategoryName",
                    ms."CategoryNameTr",
                    ms."TotalSpend",
                    COALESCE(mi."TotalIncome", 0) AS "TotalIncome",
                    CASE
                        WHEN COALESCE(mi."TotalIncome", 0) > 0 THEN (ms."TotalSpend" / mi."TotalIncome") * 100
                        ELSE 0
                    END AS "SpendPercentageOfIncome",
                    COALESCE(
                        LAG(ms."TotalSpend") OVER (PARTITION BY ms."UserId", ms."CategoryId" ORDER BY ms."Month"),
                        0
                    ) AS "PreviousMonthSpend"
                FROM MonthlySpend ms
                LEFT JOIN MonthlyIncome mi ON ms."UserId" = mi."UserId" AND ms."Month" = mi."Month";
                """);

            migrationBuilder.Sql("""
                INSERT INTO "FinancialTips" ("Topic", "Body", "Locale", "Tags", "Embedding")
                VALUES
                ('Abonelik Kontrolü', 'Kullanmadigin abonelikleri tespit et ve iptal ederek aylik nakit akisinda alan ac.', 'tr-TR', 'abonelik,nakit,task', '[0.81,0.12,0.20,0.65,0.37,0.42,0.11,0.23,0.71,0.08,0.19,0.44,0.13,0.55,0.29,0.61]'),
                ('Yeme-Disari Butcesi', 'Disarida yeme harcamalarin gelirine gore yuksekse haftalik tavan belirleyip otomatik alarm kur.', 'tr-TR', 'yeme,butce,alarm', '[0.22,0.73,0.15,0.64,0.10,0.55,0.32,0.48,0.06,0.81,0.24,0.39,0.17,0.52,0.28,0.45]'),
                ('Acil Durum Fonu', 'Her ay gelirinin en az yuzde besini ayri bir acil durum hesabina aktar.', 'tr-TR', 'acil,fund,tasarruf', '[0.49,0.31,0.78,0.14,0.62,0.27,0.19,0.44,0.58,0.36,0.11,0.67,0.23,0.72,0.05,0.40]')
                ON CONFLICT DO NOTHING;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "FinancialTips";""");
        }
    }
}
