// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wealthra.Infrastructure.Persistence;

#nullable disable

namespace Wealthra.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407120000_GlobalBilingualCategories")]
    public partial class GlobalBilingualCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2");

            // Snapshot is maintained in ApplicationDbContextModelSnapshot; this stub satisfies EF tooling.
#pragma warning restore 612, 618
        }
    }
}
