services:
  db:
    image: postgres:15-alpine
    container_name: wealthra_db_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: wealthra_user
      POSTGRES_PASSWORD: YourStrongDbPassword123!
      POSTGRES_DB: wealthra_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: wealthra-api:local
    container_name: wealthra_api_local
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=wealthra_db;Username=wealthra_user;Password=YourStrongDbPassword123!
      - JwtSettings__Secret=REPLACE_THIS_WITH_A_SUPER_SECRET_KEY_AT_LEAST_32_CHARS_LONG
      - JwtSettings__Issuer=WealthraApi
      - JwtSettings__Audience=WealthraApp
      - JwtSettings__ExpiryMinutes=60
      - ExtractionServices__OcrBaseUrl=http://ocr:8000/
      - ExtractionServices__SttBaseUrl=http://stt:8000/
      - ExtractionServices__CopilotBaseUrl=http://copilot:8000/
      - ExtractionServices__ExportBaseUrl=http://export:8000/
      - ExtractionServices__TimeoutSeconds=120
      - Groq__ApiKey=${GROQ_API_KEY}
    depends_on:
      - db
      - ocr
      - stt
      - copilot
      - export
    ports:
      - "8080:8080"
    volumes:
      - aspnet_keys_local:/root/.aspnet/DataProtection-Keys

  ocr:
    build:
      context: ./wealthra-ocr
      dockerfile: Dockerfile
    image: wealthra-ocr:local
    container_name: wealthra_ocr_local
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8001:8000"

  stt:
    build:
      context: ./wealthra-stt
      dockerfile: Dockerfile
    image: wealthra-stt:local
    container_name: wealthra_stt_local
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8002:8000"

  copilot:
    build:
      context: ./wealthra-copilot
      dockerfile: Dockerfile
    image: wealthra-copilot:local
    container_name: wealthra_copilot_local
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_URL=postgresql://wealthra_user:YourStrongDbPassword123!@db:5432/wealthra_db
    depends_on:
      - db
    ports:
      - "8003:8000"

  export:
    build:
      context: ./wealthra-export-pdf-excel
      dockerfile: Dockerfile
    image: wealthra-export:local
    container_name: wealthra_export_local
    restart: unless-stopped
    ports:
      - "8004:8000"

volumes:
  postgres_data_local:
  aspnet_keys_local:

